title: PRABHAKARAN PALANIMUTHU
description: "Data Analyst | Aspiring Data Scientist | Deep Learning & ML Enthusiast"
theme: jekyll-theme-minimal
logo: /assets/Profile Pic.png
Info:
Address: D-5, Arunalaya Flats, Joseph 2nd Street, Palavanthangal, Chennai-600114, Tamil Nadu, India
Email: prabha07lpm@gmail.com
Phone: +91 9566124655
LinkedIn: "https://www.linkedin.com/in/prabhakaran-p-7b38ab164/"

