title: PRABHAKARAN PALANIMUTHU
logo: /assets/Profile Pic.png
Address: D-5, Arunalaya Flats, Joseph 2nd Street, Palavanthangal, Chennai-600114, Tamil Nadu, India
Email: prabha07lpm@gmail.com
Phone: +91 9566124655
LinkedIn: "https://www.linkedin.com/in/prabhakaran-p-7b38ab164/"
theme: jekyll-theme-minimal
